---
- name: artifactory
  import_playbook: ../static-assignments/artifactory.yml
  tags:
    - always

  - name: import deployment file
  import_playbook: ../static-assignments/deployment.yml

# - name: include env-vars file
#   import_playbook: ../dynamic-assignments/env-vars.yml
#   tags:
#     - always

# - name: import database file
#   import_playbook: ../static-assignments/database.yml

# - name: import Loadbalancers assignment
#   import_playbook: ../static-assignments/nginx.yml
#   when: load_balancer_is_required

# - name: Tooling assignment
#   import_playbook: ../static-assignments/webservers.yml





# - name: import sonarqube file
#   import_playbook: ../static-assignments/sonarqube.yml
